### PR TITLE
fixing-price-property

### PR DESCRIPTION
**Pull request by HaroldFS**
- fixing the price property on the Product object

### CODE REVIEW

**Review by van-fs — APPROVED** [review]
LGTM. Does this imply that if the price were undefined, you'd default to $1.00?  NBD for this reference app but if something were undefined, you could init to a negative possibly to signal that something went wrong with getting the price from the backend (as opposed to a $1.00 product).

**Comment by HaroldFS** [comment]
> NBD

The default would be a dollar. Im sorry I don't completely understand. Are you recommending that there not be a default and I through an error instead?

**Comment by van-fs** [comment]
I was just thinking that the default masks an error.  Is the product a dollar because it's really priced that way or is it because something went wrong.  Alternatively if we default to -1 that seems like a clearer error signal.  Given we're not worried about actual monetary loss with our ref app, feel free to merge.

**Comment by HaroldFS** [comment]
> I was just thinking that the default masks an error. Is the product a dollar because it's really priced that way or is it because something went wrong. Alternatively if we default to -1 that seems like a clearer error signal. Given we're not worried about actual monetary loss with our ref app, feel free to merge.

Ohhh I see what you mean. That makes since 

> I was just thinking that the default masks an error. Is the product a dollar because it's really priced that way or is it because something went wrong. Alternatively if we default to -1 that seems like a clearer error signal. Given we're not worried about actual monetary loss with our ref app, feel free to merge.

i totally see what you mean I made the adjustment. Thanks! 👍

**Pull request merged**
