### PR TITLE
create-order-object

### PR DESCRIPTION
**Pull request by HaroldFS**
- create-order-object
- removed more duplicate files

### CODE REVIEW

**Review by van-fs — COMMENTED** [review]
Are the changes to all files except `Order.swift` a result of adding this file?  Or are these other changes that have somehow made it into the commit history?  I just want to be sure we're not introducing changes outside the scope of creation of the order object.

**Comment by HaroldFS** [comment]
> Are the changes to all files except `Order.swift` a result of adding this file? Or are these other changes that have somehow made it into the commit history? I just want to be sure we're not introducing changes outside the scope of creation of the order object.

These are not as a result but they are duplicate files i noticed where here when looking in finder. should I  try to add these files back and do them in another diff?

**Comment by van-fs** [comment]
I'll defer to you on whichever way preserves integrity of master.  If you want to revert and re-commit just the Order object, that may work.  Or if you wanted to create a new PR off master and add the Order object to a clean commit that'll work too.

**Comment by HaroldFS** [comment]
> I'll defer to you on whichever way preserves integrity of master. If you want to revert and re-commit just the Order object, that may work. Or if you wanted to create a new PR off master and add the Order object to a clean commit that'll work too.

I think thats a good plan 👍

**Pull request closed without merging**
